### ISSUE TITLE
Trade Items with Entity NBT Tag Not Loading

### ISSUE THREAD

**Issue by DumbXBoxAcct** [PssbleTrngle/DataTrades#13]
### What happened?

Hi - I just want to begin by telling you how much I love this mod!  The simplicity of the datapack structure for trades is fabulous and the "/villagers refresh" command sets it head and shoulders above other similar mods.

Now the issue: Using "Data Trades" v.2.1.1, I'm trying to load bee spawn eggs from "Productive Bees" v.12.2.6 as trade items for my villagers.  Any of the the eggs from the mod which have a simple item tag load and trade just fine (ex. productivebees:spawn_egg_coal_bee). 

Unfortunately, some of the eggs don't have a dedicated item tag and use a common item tag with an Entity NBT tag to qualify it (ex. productivebees:spawn_egg_configurable_bee{EntityTag:{type:"productivebees:diamond"}} ).  These tags for the  spawn eggs with Entity NBT tags won't load as trades in "Data Trades," even though I know that the syntax of the entire tag is correct, because it works perfectly from the command line with a "/give" command.

Am I doing something wrong or does "Data Trades" not support NBT tags and/or Entity tags?

### Loader

forge

### Mod Version

47.2.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
The data ingredients use the default Ingredient (as in recipes) json behaviour, which does not support NBT as far as I know.
You can modify the nbt of an item using the `minecraft:set_nbt` [item modifier function](https://minecraft.wiki/w/Item_modifier)

**Comment by DumbXBoxAcct** [comment]
This worked great, thanks for your help!
