### ISSUE TITLE
Some Mods Which Add Villager Professions Don't Use Namespaces in Paths

### ISSUE THREAD

**Issue by DumbXBoxAcct** [PssbleTrngle/DataTrades#14]
### What happened?

I've been following the "data/[namespace]/villager/professions/[path].json" example which you gave in the wiki for several mods which add villager professions and have not been able to get either simple trades in the profession's JSON file or referenced trades, in separate JSON files in the some of the mods' respective "trades" subfolders, to load specified trades. 

To test everything, I've been running Data Trades 2.1.1 with OptiFine HD U16 and only the mods which add professions and their supporting APIs, on Forge 47.2.0, for Minecraft JE 1.20.1. I've attached two datapacks which demonstrate the issue: "datatrades_which_work.zip" and "datatrades_not_working.zip". Hopefully they'll help demonstrate what I'm describing.

Mods which have the issue are: 

"Beekeeper" (namespace: "bk")
"Belgies Mo'Villagers" (namespace: "redstonevillager")
"More Villagers" (namespace: "morevillagers")
"Vinery" (namespace: "vinery")
"Productive Bees" (namespace: "productivebees"). 

Mods which don't have the issue and which work properly with a path including their namesspaces are: 

"Dyeable Redstone Signal"
"The Firework Fun Mod".

I also tried referencing the trades files three different ways, without success. To reference "data/productivebees/villager/trades/wheat.json" in the "data/productivebees/villager/professions/beekeeper.json" file, I tried and the trades didn't show for the beekeeper profession.

a. "productivebees:wheat"
b. "minecraft:wheat"
c: "wheat"

Oddly, if I create the files in the "data/minecraft/villager/professions/ or "data/minecraft/villager/trades/ folders, then reference the wheat.json file as just "wheat", it works!  Likewise, if I skip the separate trade file and just put the transaction directly into the "data/minecraft/villager/professions/beekeeper.json" file, it also works.

Could be that I'm doing something, hoping that's the case. Thanks for any help or direction you can give me on this!
[datatrades_that_work.zip](https://github.com/PssbleTrngle/DataTrades/files/13856378/datatrades_that_work.zip)
[datatrades_not_working.zip](https://github.com/PssbleTrngle/DataTrades/files/13856379/datatrades_not_working.zip)

### Loader

forge

### Mod Version

2.1.1

### Minecraft Version

1.20

**Comment by DumbXBoxAcct** [comment]
[latest.log](https://github.com/PssbleTrngle/DataTrades/files/13856383/latest.log)
[debug.log](https://github.com/PssbleTrngle/DataTrades/files/13856384/debug.log)

**Comment by PssbleTrngle** [comment]
The default namespace should then just being the "minecraft" namespace, as ID-wise, "beekeeper" is equivalent to "minecraft:beekeeper"

**Comment by DumbXBoxAcct** [comment]
Thanks for your quick response Niklas!  I guess I’ll just work with it that way then, I appreciate your help, I’ll close the ticket out.- GordonOn Jan 8, 2024, at 9:13 AM, Niklas Widmann ***@***.***> wrote:﻿
The default namespace should then just being the "minecraft" namespace, as ID-wise, "beekeeper" is equivalent to "minecraft:beekeeper"
