### ISSUE TITLE
Take types

### ISSUE THREAD

**Issue by SlavaTalanov** [PssbleTrngle/DataTrades#15]
### Describe the feature you have in mind.

There is no documentation about what "type": "constant" entails and what the alternatives are.

**Comment by PssbleTrngle** [comment]
The README section about the `Trade` object links to the documentation about NumberProviders on the minecraft wiki, where the different types are explained. Although it still links to the old fandom wiki which I should update.
[Here is the link on the new wiki](https://minecraft.wiki/w/Loot_table#Number_provider)
