### ISSUE TITLE
Min/max randomized count

### ISSUE THREAD

**Issue by ginsm** [PssbleTrngle/DataTrades#17]
### Describe the feature you have in mind.

It'd be nice if you had the option to set a min/max for the TradeIngredient count and the code would pick a number within the given range.

### Does this solve a particular problem?

It brings the mod's functionality closer to vanilla trades, as some trades do have quantity ranges.

**Comment by PssbleTrngle** [comment]
You should be able to do that using the `minecraft:set_count` function, you can find documentation about it on the [wiki](https://minecraft.wiki/w/Item_modifier)

**Comment by ginsm** [comment]
Awesome, thanks for the info. :)
