### ISSUE TITLE
Wandering Traders only take one rare trade regardless of value in wandering.json file

### ISSUE THREAD

**Issue by CraftyG** [PssbleTrngle/DataTrades#7]
## Expectation
From the wandering trader example data pack, 2 trades should be chosen from the rare pool.
```json
  "rare": {
    "take": {
      "type": "constant",
      "value": 2
    },
    "trades": [
      {
        "sells": {
          "item": "chainmail_boots"
        },
        "wants": [
          {
            "item": "lapis_lazuli",
            "count": 14
          }
        ]
      }, {
        "sells": {
          "item": "chainmail_chestplate"
        },
        "wants": [
          {
            "item": "lapis_lazuli",
            "count": 14
          }
        ]
      }, {
 ```
 ## Observation
 Only one trade has been chosen. Changing the values to higher numbers has no effect.

![2023-09-25_13 14 06](https://github.com/PssbleTrngle/DataTrades/assets/53879030/f82cd0cd-32a4-4dde-af4c-cbf15b1faf73)

### Loader

forge

### Mod Version

1.1.0

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
Yes, right now the wandering trader always only takes one trade, because I did not yet find a good solution to overwrite that, but I look into it

**Comment by PssbleTrngle** [comment]
Release an update that should fix this
